<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>{{ $thread->title ?: 'Socius Chat Export' }}</title>
    <style>
        body {
            font-family: 'Helvetica', 'Arial', sans-serif;
            line-height: 1.6;
            color: #333;
            margin: 40px;
        }

        .header {
            border-bottom: 2px solid #fbbf24;
            padding-bottom: 10px;
            margin-bottom: 30px;
        }

        .header h1 {
            margin: 0;
            color: #1a1a1a;
            font-size: 24px;
        }

        .header p {
            margin: 5px 0 0;
            font-size: 12px;
            color: #666;
        }

        .message {
            margin-bottom: 30px;
            padding: 15px;
            border-radius: 10px;
        }

        .message-user {
            background-color: #fef3c7;
            border-left: 4px solid #fbbf24;
        }

        .message-socius {
            background-color: #f8fafc;
            border-left: 4px solid #94a3b8;
        }

        .role {
            font-weight: bold;
            font-size: 12px;
            text-transform: uppercase;
            margin-bottom: 5px;
            color: #444;
        }

        .meta {
            font-size: 10px;
            color: #888;
            margin-bottom: 10px;
        }

        .content {
            font-size: 14px;
            white-space: pre-wrap;
        }

        table {
            width: 100%;
            border-collapse: collapse;
            margin: 15px 0;
        }

        table th,
        table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
            font-size: 12px;
        }

        table th {
            background-color: #f1f5f9;
        }
    </style>
</head>

<body>
    <div class="header">
        <h1>{{ $thread->title ?: 'Socius Chat Export' }}</h1>
        <p>Exported on {{ now()->toDayDateTimeString() }} | User: {{ Auth::user()->name }}</p>
    </div>

    @foreach($messages as $message)
        <div class="message {{ $message->role === 'user' ? 'message-user' : 'message-socius' }}">
            <div class="role">{{ $message->role === 'user' ? 'User' : 'Socius' }}</div>
            <div class="meta">{{ $message->created_at->format('Y-m-d H:i') }}</div>
            <div class="content">{!! nl2br(e($message->content)) !!}</div>
        </div>
    @endforeach

    <div style="text-align: center; font-size: 10px; color: #aaa; margin-top: 50px;">
        Generated by KM Survey Tool — Socius AI
    </div>
</body>

</html>