<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Response #{{ $response->id }} - {{ $survey->title }}</title>
    <style>
        body {
            font-family: 'Helvetica', sans-serif;
            color: #1f2937;
            line-height: 1.5;
            padding: 20px;
        }

        .header {
            border-bottom: 2px solid #dc2626;
            padding-bottom: 20px;
            margin-bottom: 30px;
        }

        .org-name {
            font-size: 24px;
            font-weight: bold;
            color: #dc2626;
        }

        .report-title {
            font-size: 18px;
            color: #6b7280;
            margin-top: 5px;
        }

        .meta-grid {
            margin-bottom: 30px;
            background: #f9fafb;
            padding: 20px;
            border-radius: 8px;
        }

        .meta-item {
            margin-bottom: 10px;
        }

        .meta-label {
            font-weight: bold;
            color: #6b7280;
            width: 150px;
            display: inline-block;
        }

        .answer-section {
            margin-bottom: 20px;
            border-bottom: 1px solid #f3f4f6;
            padding-bottom: 15px;
        }

        .question-text {
            font-weight: bold;
            color: #111827;
            margin-bottom: 8px;
            font-size: 14px;
        }

        .answer-value {
            font-size: 13px;
            color: #374151;
        }

        .signature-img {
            max-height: 80px;
            border: 1px solid #eee;
            margin-top: 5px;
        }

        .media-img {
            max-height: 200px;
            border-radius: 8px;
            margin-top: 10px;
        }

        .footer {
            margin-top: 50px;
            font-size: 10px;
            color: #9ca3af;
            text-align: center;
        }
    </style>
</head>

<body>
    <div class="header">
        <div class="org-name">{{ $branding['org_name'] ?? config('app.name') }}</div>
        <div class="report-title">Individual Response Detail: #{{ $response->id }}</div>
    </div>

    <div class="meta-grid">
        <div class="meta-item"><span class="meta-label">Survey:</span> {{ $survey->title }}</div>
        <div class="meta-item"><span class="meta-label">Submitted On:</span>
            {{ $response->created_at->format('F d, Y \a\t H:i:s') }}</div>
        <div class="meta-item"><span class="meta-label">Respondent:</span>
            {{ $response->respondent->name ?? 'Anonymous' }}</div>
        <div class="meta-item"><span class="meta-label">Email:</span> {{ $response->respondent->email ?? 'N/A' }}</div>
    </div>

    @foreach($answers as $ans)
        <div class="answer-section">
            <div class="question-text">{{ $ans['label'] }}</div>
            <div class="answer-value">
                @php
                    $val = $ans['value'];
                    $valStr = is_array($val) ? json_encode($val) : (string) $val;
                    $isSignature = str_contains($valStr, 'base64,');
                    $isMedia = str_starts_with($valStr, 'uploads/');
                    $isImage = $isMedia && in_array(strtolower(pathinfo($valStr, PATHINFO_EXTENSION)), ['jpg', 'jpeg', 'png', 'gif', 'webp']);
                @endphp

                @if($isSignature)
                    <img src="{{ $valStr }}" class="signature-img">
                @elseif($isImage)
                    <img src="{{ public_path('storage/' . $valStr) }}" class="media-img">
                @elseif($isMedia)
                    <span style="color: #dc2626;">[Media File: {{ $valStr }}]</span>
                @else
                    {{ is_array($val) ? implode(', ', $val) : $val }}
                @endif
            </div>
        </div>
    @endforeach

    <div class="footer">
        Generated by KDAnalytiks on {{ date('Y-m-d H:i:s') }}
    </div>
</body>

</html>